apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  database-client: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
  database-host: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
  database-port: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
  database-username: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
  database-password: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
  database-name: {{ .Files.Get "values-secrets.yaml" | b64enc | quote }}
